### ISSUE TITLE
Crash on project sheet templates 

### ISSUE THREAD

**Issue by Karmak23** [CommonsDev/dataserver#42]
Salut à tous,

j'ai [un crash](http://dev.1flow.net/commonsdev/dataserver-dev/group/61738/), en tant qu'admin, quand je search des templates :

```
[30/Jun/2015 16:14:54] "GET /api/v0/project/sheet/template/?slug=is HTTP/1.1" 500 164018
```
Quand je suis anonyme dans le navigateur, tout marche bien, la requête se fait normalement et le résultat est bon…
Est-ce que vous auriez une piste ? J'ai déjà cherché sur le net, mais rien trouvé.

**Comment by glibersat** [comment]
Ca ressemble à une mauvaise utilisation/invocation du paginator car tu te retrouves à tester la longueur d'un booléen. Peut-être un bug au niveau des resources tastypie de la fiche projet ? (regarder dans les méthodes surchargées)

**Comment by Karmak23** [comment]
Mouais c'est bien ça le problème, il n'y a aucune methode surchargée.
Comme j'ai le cerveau en compote après 3h de dév, je fais une pause, je pense que demain la solution va me sauter aux yeux… Concrètement il n'y a pas d'appel direct ou surchargé au paginateur dans `projectsheet`, je ne comprends pas comment il fait pour fonctionner en anon et pas en authentifié. Ptet un bug dans la permission liée à la liste…
Merci Gui,

**Comment by Karmak23** [comment]
Fixed in upcoming b8df628345130a38cef3d5f1149529ac1bc07ba7
